### ISSUE TITLE
call a make file 

### ISSUE THREAD

**Issue by joe-getcouragenow** [naiba/nocd#11]
can this CI be used to get a github hook and then call a makefile for building my golang code ?

the make file does all the packaging and pushing releases to my own s3 server.

--

also the GUi is in chinese. I guess i will just have to use google translate for now :)

**Comment by naiba** [comment]
Yes, you can use it like this.  Unfortunately, only Chinese is available now and there is no plan to do i18n.  According to the scenario you describe, you can check GitHub Actions, and you can also achieve your needs.

**Comment by joe-getcouragenow** [comment]
thanks @naiba 

Will try it out.

Regarding i18n:
1. https://phrase.com/blog/posts/internationalisation-in-go-with-go-i18n/
- will work on your .html, if we just convert into standard golang templates
2. https://github.com/getcouragenow/bootstrap/tree/master/tool/i18n
- This can auto translate the files from a JSON file. Works well and we have used it for Chinese.
- It is used for this: https://maintemplate.ci.getcouragenow.org/#/settings
  - Change "Language" and it you will see.

**Comment by naiba** [comment]
@joe-getcouragenow Oh wow seems that is an easy way get into I18n.

If you translate the readme.md to English, I'll I
Put the i18n package into NoCD and export the Chinese string to a single JSON file, then you can translate it. 😁

**Comment by joe-getcouragenow** [comment]
[README_Chinese.md.txt](https://github.com/naiba/nocd/files/5177989/README_Chinese.md.txt)

Just drop into root.

**Comment by naiba** [comment]
Nice work. Thanks for the translation. I'll start work on i18n.

**Comment by naiba** [comment]
Hi @joe-getcouragenow
I'm glad to tell you that the multilingual support is now complete 4094ae6 and you can start using it. Feedback is welcome.

**Comment by joe-getcouragenow** [comment]
Hey @naiba Wow that fast. Had a look and it looks great.

How did you make the English text ? you did not use the tool we build ?
https://github.com/getcouragenow/bootstrap/tree/master/tool/i18n

I ask because we can easily translate into all languages with that tool as part of a make file.

**Comment by naiba** [comment]
@joe-getcouragenow 

Because I need to make the key name of i18n meaningful, which is equivalent to translating it again, so I translated it by the way.

**Comment by joe-getcouragenow** [comment]
Ok. Will close for now i think.

I ran the code here now. All works for now.

Will make other issues and help fix a few thngs.
