### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by joe-getcouragenow** [naiba/nocd#12]
We dont have to do this but for zero CGO we can use this DB.

https://github.com/genjidb/genji

It works very well and runs badger under the hood.

here is what it can do: https://github.com/genjidb/genji/blob/master/docs/content/en/docs/genji-sql/selecting-documents.md

I just noticed that you use GORM here: https://github.com/naiba/nocd/blob/master/sqlite3/pipeline.go
- genji does not work with it offically though.

But as you can see in the example genjo can do mapping of the sql data into the go structs
https://github.com/genjidb/genji/blob/master/example_test.go#L43

**Comment by naiba** [comment]
I think this project still has room for growth, let us wait for him for a while.

**Comment by naiba** [comment]
By the way, can I know what to ask for zero CGO?

**Comment by joe-getcouragenow** [comment]
CGO means that the golang code needs to call c ++ or c, like with sqlite.

sure we can wait.

genji works really well for our project. I have not benchmarked it against sqlite, but with no CGO its very likely to be faster at runtime. But for development its much easier.

**Comment by naiba** [comment]
Sqlite is only an option in the rapid development stage. After running for a period of time, the data volume becomes large. We can quickly provide other gorm-supported database options, such as MySQL/postgresql, to suit the current data scale.

**Comment by joe-getcouragenow** [comment]
Sure i hear you. We can use SQLite. No big problem for us.

On other projects we avoid those complex solutions and us this:
https://github.com/mkawserm/flamed
which uses this: https://github.com/lni/dragonboat

Its give you a DB that is HA. We stand this up in 3 DC ( data centers) around the world and any DC can fail and it all keeps going and recovers when the DC Recovers. 
Its just badger under the hood just like genji is badger under the hood.

**Comment by naiba** [comment]
Sqlite is already light and powerful enough, we need to strike a balance. If you can implement a gorm adapter for genji/flamed, it will become very simple.

**Comment by gedw99** [comment]
a gorm adapter for genji is happening in the genji repo now.
