### ISSUE TITLE
Should we embed the web assets using statik ?

### ISSUE THREAD

**Issue by joe-getcouragenow** [naiba/nocd#13]
Will make the deployment easier because everything is one binary.

github.com/rakyll/statik

Or other one that does the same thing. I bet Gin has a standard way to do embedding ?
like this: https://github.com/gin-gonic/contrib/blob/master/static/example/bindata/example.go

**Comment by naiba** [comment]
Why not use docker? Previously, static files were packaged into binary files, but they were removed later.

**Comment by joe-getcouragenow** [comment]
We dont run docker as we dont need it. I dont want to introduce docker just because of noCD.

Embeding is pretty easy.

**Comment by joe-getcouragenow** [comment]
https://github.com/gin-gonic/gin#build-a-single-binary-with-templates

**Comment by naiba** [comment]
Sorry, this has been done before. Packing resource files will make local debugging no longer easy, and there is no more energy to deal with.
