### ISSUE TITLE
Support Gitea

### ISSUE THREAD

**Issue by joe-getcouragenow** [naiba/nocd#14]
Watching here: https://github.com/go-playground/webhooks/pull/81

**Comment by naiba** [comment]
NoCD supports gogs webhook. I compared https://github.com/gogs/gogs/blob/main/internal/db/webhook.go and https://github.com/go-gitea/gitea/blob/master/models/webhook.go is unchanged, you can try to add it as a gogs project, and then test the webhook callback, it should work.

**Comment by joe-getcouragenow** [comment]
AH cool.  Nice one
